image: node:lts

before_script:
  - npm install

pages: 
  cache:
    paths:
      - node_modules/
  script:
      - npm run build
  artifacts:
    paths:
      - public
  rules: 
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
  only: 
    - main
